# Generated by Django 4.2 on 2023-05-24 17:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', upload_to=app.models.user_directory_path),
        ),
    ]
