# Generated by Django 4.2 on 2023-05-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_message_conversation_delete_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='min_age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_age_preference',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='min_age_preference',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
