# Generated by Django 4.2 on 2023-05-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_message_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(max_length=50)),
                ('font_family', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='message',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.messagestyle'),
        ),
    ]
