# Generated by Django 4.2 on 2023-05-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_messagestyle_alter_message_body_message_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='style',
        ),
        migrations.AddField(
            model_name='message',
            name='font_family',
            field=models.CharField(blank=True, choices=[('MonteCarlo', 'MonteCarlo')], max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='font_size',
            field=models.CharField(blank=True, choices=[('12px', 'Small'), ('16px', 'Medium'), ('20px', 'Large')], max_length=5),
        ),
        migrations.DeleteModel(
            name='MessageStyle',
        ),
    ]
