# Generated by Django 4.2 on 2023-05-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_message_style_message_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='background_image',
            field=models.CharField(blank=True, choices=[('image/message_background.png', 'Zdjęcie 1'), ('image/message_background2.png', 'Zdjęcie 2'), ('image/message_background3.png', 'Zdjęcie 3'), ('image/message_background4.png', 'Zdjęcie 4')], max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='extra_image',
            field=models.CharField(blank=True, choices=[('image/flower1.png', 'Kwiatek 1'), ('image/flower2.png', 'Kwiatekj 2'), ('image/teardrop.png', 'Łza'), ('image/kiss.png', 'Buziak')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='font_family',
            field=models.CharField(blank=True, choices=[('AlexBrush', 'AlexBrush'), ('DancingScript', 'DancingScript'), ('Ephesis', 'Ephesis'), ('GreatVibes', 'GreatVibes'), ('MonteCarlo', 'MonteCarlo'), ('Parisienne', 'Parisienne'), ('PetitFormalScript', 'PetitFormalScript')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='font_size',
            field=models.CharField(blank=True, choices=[('20px', '20px'), ('30px', '30px'), ('35px', '35px'), ('40px', '40px')], max_length=5),
        ),
    ]
