# Generated by Django 4.2 on 2023-05-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_message_background_image_message_extra_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='background_image',
        ),
    ]
