# Generated by Django 4.2 on 2023-05-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_message_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='extra_image',
            new_name='picture',
        ),
    ]
