# Generated by Django 4.2 on 2023-05-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_extra_image_message_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='font_family',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='font_size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.CharField(max_length=100),
        ),
    ]
