# Generated by Django 4.2 on 2023-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_message_font_family_alter_message_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='font_family',
            field=models.CharField(blank=True, choices=[('AlexBrush', 'AlexBrush'), ('DancingScript', 'DancingScript'), ('Ephesis', 'Ephesis'), ('GreatVibes', 'GreatVibes'), ('MonteCarlo', 'MonteCarlo'), ('Parisienne', 'Parisienne'), ('PetitFormalScript', 'PetitFormalScript')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='font_size',
            field=models.CharField(blank=True, choices=[('20px', '20px'), ('30px', '30px'), ('35px', '35px'), ('40px', '40px')], max_length=5),
        ),
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.CharField(blank=True, choices=[('', '- - -'), ('image/flower1.png', 'Kwiatek 1'), ('image/flower2.png', 'Kwiatekj 2'), ('image/teardrop.png', 'Łza'), ('image/kiss.png', 'Buziak'), ('image/hair.png', 'Kosmyk włosów')], max_length=20),
        ),
    ]
