# Generated by Django 4.2 on 2023-05-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_message_font_family_alter_message_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.CharField(blank=True, choices=[('', '- - -'), ('images/flower1.png', 'Kwiatek 1'), ('images/flower2.png', 'Kwiatekj 2'), ('images/teardrop.png', 'Łza'), ('images/kiss.png', 'Buziak'), ('images/hair.png', 'Kosmyk włosów')], max_length=20),
        ),
    ]
