# Generated by Django 4.2 on 2023-05-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_message_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='font_family',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='font_size',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
